### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by BlackTurtle123** [jansenmarc/WavesGatewayLTCExample#2]
```
Traceback (most recent call last):
  File "/home/litecoin/.local/lib/python3.6/site-packages/waves_gateway/service/transaction_polling_service.py", line 127, in _run
    self._iteration()
  File "/home/litecoin/.local/lib/python3.6/site-packages/waves_gateway/service/transaction_polling_service.py", line 209, in _iteration
    transactions = self._chain_query_service.get_transactions_of_block_at_height(current_height)
  File "/home/litecoin/.local/lib/python3.6/site-packages/waves_gateway/service/chain_query_service_converter_proxy_impl.py", line 38, in get_transactions_of_block_at_height
    transactions = self._chain_query_service.get_transactions_of_block_at_height(height)
  File "/home/litecoin/TurtleNodeGatewayLTC/waves_litecoin_gateway/lib/litecoin_chain_query_service.py", line 94, in get_transactions_of_block_at_height
    return [a for a in get_transaction_tasks.map(self.get_transaction, block['tx'])]
  File "/home/litecoin/.local/lib/python3.6/site-packages/gevent/pool.py", line 333, in map
    return list(self.imap(func, iterable))
  File "/home/litecoin/.local/lib/python3.6/site-packages/gevent/pool.py", line 104, in next
    raise value.exc
  File "/home/litecoin/.local/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/litecoin/TurtleNodeGatewayLTC/waves_litecoin_gateway/lib/litecoin_chain_query_service.py", line 84, in get_transaction
    transaction_sender = self._resolve_senders(transaction)
  File "/home/litecoin/TurtleNodeGatewayLTC/waves_litecoin_gateway/lib/litecoin_chain_query_service.py", line 70, in _resolve_senders
    if 'addresses' not in vin_transaction['vout'][vin['vout']]['scriptPubKey']:
IndexError: list index out of range
```

**Comment by BlackTurtle123** [comment]
TX that gave exception
`{'txid': 'c3dc753a28b280ff912a7992f2a3a110c244138afd7052769571bf446e992b2c', 'hash': 'c3dc753a28b280ff912a7992f2a3a110c244138afd7052769571bf446e992b2c', 'version': 1, 'size': 225, 'vsize': 225, 'locktime': 0, 'vin': [], 'vout': [{'value': Decimal('25709395807.57424897'), 'n': 0, 'scriptPubKey': {'asm': '0683293c9363962c6255c170206aae4f3256c3af91540f0100000000ffffffff0268890b010000000016001402a3d31edb073a929d5b42bac73fc2a55c797b8d9ca2f606000000001976 OP_HASH160 45bb22ed11f5937cdae558af6a846b078922c5f8 OP_EQUALVERIFY OP_CHECKSIG 12359 02206e48d89ca1eb751b1417a49407e0edbb18d6752f6ebbec08399611c5721ae61902202de79d750a1f840eec7e21e61b4e92954e0bc46191c681481aa33e3f43a9b4cb 33 -936479 a4529c4e18 af98c80887f25f aa41ac9a2c945d2536949ec6 OP_RIPEMD160 OP_NUMNOTEQUAL', 'hex': '4a0683293c9363962c6255c170206aae4f3256c3af91540f0100000000ffffffff0268890b010000000016001402a3d31edb073a929d5b42bac73fc2a55c797b8d9ca2f606000000001976a91445bb22ed11f5937cdae558af6a846b078922c5f888ac0247304402206e48d89ca1eb751b1417a49407e0edbb18d6752f6ebbec08399611c5721ae61902202de79d750a1f840eec7e21e61b4e92954e0bc46191c681481aa33e3f43a9b4cb0121031f4a8e05a4529c4e1807af98c80887f25f0caa41ac9a2c945d2536949ec6a69e', 'type': 'nonstandard'}}]}`
